version: 0.2

phases:
  install:
    commands:
      - npm install
      - node -v
      - npm -v
      - yarn -v
  pre_build:
    commands:
      - echo Entring app directory
      - cd old-maid-cheatable
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - cd old-maid-cheatable
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: old-maid-cheatable/build
