version: 0.2

phases:
  install:
    commands:
      - npm install
      - node -v
      - npm -v
      - yarn -v
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
